artifact:
  root_dir: artifact

layout_parser:
  root_dir: layout_parser
  whl_url: https://paddleocr.bj.bcebos.com/whl/layoutparser-0.0.0-py3-none-any.whl


pdf_saver:
  root_dir: pdf_saver
  file_name: raw.pdf
  images_dir_name: images

teble_detector:

  root_dir: teble_detector
  teble_detector_imgs_dir_name: table_images

text_extractor:
  root_dir: text_extractor
  csv_dir_name: all_csv
  final_excel_file_name: final.xlsx




